export enum ProjectCategory {
  FOOD = "FOOD",
  HEALTH = "HEALTH",
  EDUCATION = "EDUCATION",
  ENVIRONMENT = "ENVIRONMENT",
  RELIGION = "RELIGION",
  HUMANITARIAN = "HUMANITARIAN",
  HOUSING = "HOUSING",
  OTHER = "OTHER"
}
