version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "8081:8080"
    environment:
      - DOMAIN_NAME=http://localhost:
      - API_PORT=8081
    depends_on:
      - api

  api:
    image: your-api-image
    ports:
      - "8080:8080"
    environment:
      - DOMAIN_NAME=http://localhost:
      - API_PORT=8080
