/* tslint:disable */
/* eslint-disable */
/**
 * Charitan Authentication API
 * API documentation for Charitan\'s authentication service.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AuthDto
 */
export interface AuthDto {
  /**
   *
   * @type {string}
   * @memberof AuthDto
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof AuthDto
   */
  password: string;
}

/**
 * Check if a given object implements the AuthDto interface.
 */
export function instanceOfAuthDto(value: object): value is AuthDto {
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("password" in value) || value["password"] === undefined) return false;
  return true;
}

export function AuthDtoFromJSON(json: any): AuthDto {
  return AuthDtoFromJSONTyped(json, false);
}

export function AuthDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuthDto {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"],
  };
}

export function AuthDtoToJSON(json: any): AuthDto {
  return AuthDtoToJSONTyped(json, false);
}

export function AuthDtoToJSONTyped(
  value?: AuthDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    password: value["password"],
  };
}
