/* tslint:disable */
/* eslint-disable */
/**
 * Charitan Authentication API
 * API documentation for Charitan\'s authentication service.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Claim
 */
export interface Claim {
  /**
   *
   * @type {string}
   * @memberof Claim
   */
  claim: string;
}

/**
 * Check if a given object implements the Claim interface.
 */
export function instanceOfClaim(value: object): value is Claim {
  if (!("claim" in value) || value["claim"] === undefined) return false;
  return true;
}

export function ClaimFromJSON(json: any): Claim {
  return ClaimFromJSONTyped(json, false);
}

export function ClaimFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Claim {
  if (json == null) {
    return json;
  }
  return {
    claim: json["claim"],
  };
}

export function ClaimToJSON(json: any): Claim {
  return ClaimToJSONTyped(json, false);
}

export function ClaimToJSONTyped(
  value?: Claim | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    claim: value["claim"],
  };
}
